services:
  - type: web
    name: unifix-api
    env: node
    rootDirectory: backend
    buildCommand: npm install
    startCommand: ./render-build.sh
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://yash:yash@cluster0.zkumq4a.mongodb.net/unifix
      - key: PORT
        value: 10000 